"""initial schema

Revision ID: 4e7319ee48f6
Revises: 
Create Date: 2026-09-04 15:33:24.272400
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4e7319ee48f6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('interval_minutes', sa.Integer(), server_default='180', nullable=False),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('round_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connected_by', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_is_active'), ['is_active'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('role', sa.String(length=16), server_default='user', nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('asked_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_asked_questions_chat_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_asked_questions_question_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asked_questions')),
    sa.UniqueConstraint('chat_id', 'question_id', 'round_number', name=op.f('uq_asked_questions_chat_id_question_id_round_number'))
    )
    with op.batch_alter_table('asked_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asked_questions_chat_id'), ['chat_id'], unique=False)

    op.create_table('group_polls',
    sa.Column('poll_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('correct_option_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_group_polls_chat_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_group_polls_question_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poll_id', name=op.f('pk_group_polls'))
    )
    with op.batch_alter_table('group_polls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_polls_chat_id'), ['chat_id'], unique=False)

    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_options_question_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_options')),
    sa.UniqueConstraint('question_id', 'position', name=op.f('uq_question_options_question_id_position'))
    )
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)

    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quiz_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_sessions'))
    )
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('random_question_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_random_question_issues_question_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_random_question_issues_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_random_question_issues'))
    )
    with op.batch_alter_table('random_question_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_random_question_issues_user_id'), ['user_id'], unique=False)

    op.create_table('user_daily_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_date', sa.Date(), nullable=False),
    sa.Column('quiz_starts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('random_questions', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_daily_limits_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_daily_limits')),
    sa.UniqueConstraint('user_id', 'quiz_date', name=op.f('uq_user_daily_limits_user_id_quiz_date'))
    )
    with op.batch_alter_table('user_daily_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_daily_limits_quiz_date'), ['quiz_date'], unique=False)

    op.create_table('user_daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_date', sa.Date(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('correct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_daily_stats_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_daily_stats')),
    sa.UniqueConstraint('user_id', 'quiz_date', name=op.f('uq_user_daily_stats_user_id_quiz_date'))
    )
    with op.batch_alter_table('user_daily_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_daily_stats_quiz_date'), ['quiz_date'], unique=False)

    op.create_table('user_topic_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_topic_preferences_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_topic_preferences')),
    sa.UniqueConstraint('user_id', 'category', name=op.f('uq_user_topic_preferences_user_id_category'))
    )
    with op.batch_alter_table('user_topic_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_topic_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('user_total_stats',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('correct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_total_stats_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_total_stats'))
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('poll_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('counted', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quiz_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['random_question_issues.id'], name=op.f('fk_answers_issue_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answers_question_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], name=op.f('fk_answers_session_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_answers_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers'))
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_quiz_date'), ['quiz_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_answers_user_quiz_date', ['user_id', 'quiz_date'], unique=False)
        batch_op.create_index('uq_answers_issue', ['issue_id'], unique=True)
        batch_op.create_index('uq_answers_poll_user', ['poll_id', 'user_id'], unique=True)
        batch_op.create_index('uq_answers_session_question', ['session_id', 'question_id'], unique=True)

    op.create_table('session_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_session_questions_question_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], name=op.f('fk_session_questions_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_questions')),
    sa.UniqueConstraint('session_id', 'position', name=op.f('uq_session_questions_session_id_position')),
    sa.UniqueConstraint('session_id', 'question_id', name=op.f('uq_session_questions_session_id_question_id'))
    )
    with op.batch_alter_table('session_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_questions_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_questions_session_id'))

    op.drop_table('session_questions')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index('uq_answers_session_question')
        batch_op.drop_index('uq_answers_poll_user')
        batch_op.drop_index('uq_answers_issue')
        batch_op.drop_index('ix_answers_user_quiz_date')
        batch_op.drop_index(batch_op.f('ix_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_answers_quiz_date'))

    op.drop_table('answers')
    op.drop_table('user_total_stats')
    with op.batch_alter_table('user_topic_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_topic_preferences_user_id'))

    op.drop_table('user_topic_preferences')
    with op.batch_alter_table('user_daily_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_daily_stats_quiz_date'))

    op.drop_table('user_daily_stats')
    with op.batch_alter_table('user_daily_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_daily_limits_quiz_date'))

    op.drop_table('user_daily_limits')
    with op.batch_alter_table('random_question_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_random_question_issues_user_id'))

    op.drop_table('random_question_issues')
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_sessions_user_id'))

    op.drop_table('quiz_sessions')
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_options_question_id'))

    op.drop_table('question_options')
    with op.batch_alter_table('group_polls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_polls_chat_id'))

    op.drop_table('group_polls')
    with op.batch_alter_table('asked_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asked_questions_chat_id'))

    op.drop_table('asked_questions')
    op.drop_table('users')
    op.drop_table('settings')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_is_active'))
        batch_op.drop_index(batch_op.f('ix_questions_category'))

    op.drop_table('questions')
    op.drop_table('chats')
    # ### end Alembic commands ###
